Tools R us Sale/Team2WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Team2WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Tools R us Sale/Team2WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Team2WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Tools R us Sale/Team2WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Team2WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Tools R us Sale/Team2WebApp/Pages/Shared/Sales/Sale.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SalesSystem.BLL;
using SalesSystem.ViewModels;

namespace Team2WebApp.Pages.Shared.Sales
{
    public class SaleModel : PageModel
    {
        private readonly CategoryServices _categoryServices;
        private readonly StockItemServices _stockItemServices;


        public SaleModel(CategoryServices categoryServices, StockItemServices stockItemServices)
        {
            _categoryServices = categoryServices;
            _stockItemServices = stockItemServices;
        }

        [TempData]
        public string Feedback { get; set; }

        [BindProperty]
        public List<FetchCategory> Categories { get; set; }

        [BindProperty]
        public List<StockItem> StockItems { get; set; }

        [BindProperty]
        public List<SaleCart> SaleCarts { get; set; }

        [BindProperty] public int CategoryId { get; set; }

        [BindProperty] public int StockItemID { get; set; }

        [BindProperty] public bool Shopping { get; set; }
        [BindProperty] public bool ViewCart { get; set; }
        [BindProperty] public bool Checkout { get; set; }

        public void OnGet()
        {
            PopulateCategories();
            Shopping = true;
        }

        public void PopulateCategories()
        {
            Categories = _categoryServices.Category_GetList();
        }

        public IActionResult OnPostCategoryItems()
        {
            PopulateCategories();

            StockItems = _stockItemServices.Product_GetProductByCategory(CategoryId);
            
            Shopping = true;
            ViewCart = false;
            Checkout = false;

            return Page();
        }

        public IActionResult OnPostAddItems()
        {
            SaleCart saleCart = StockItems
                                    .Where(x => x.StockItemID == StockItemID)
                                    .Select(x => new SaleCart
                                    {
                                       StockItemID = x.StockItemID,
                                       Description = x.Description,
                                       price = x.price,
                                       Quantity = 1,
                                       Total = x.price
                                    })
                                    .FirstOrDefault();
            
            if (SaleCarts.Count() > 0)
            {
                bool itemExists = SaleCarts
                                    .Where(x => x.StockItemID == saleCart.StockItemID)
                                    .Any();

                if (itemExists)
                {
                    Feedback = "Item exists.";
                }
                else
                {
                    SaleCarts.Add(saleCart);
                }
            }
            else
            {
                SaleCarts.Add(saleCart);
            }
            
            PopulateCategories();

            Shopping = true;
            ViewCart = false;
            Checkout = false;

            return Page();
        }

        public IActionResult OnPostShopping()
        {
            PopulateCategories();

            Shopping = true;
            ViewCart = false;
            Checkout = false;

            return Page();
        }

        public IActionResult OnPostCart()
        {
            Shopping = false;
            ViewCart = true;
            Checkout = false;

            return Page();
        }

        public IActionResult OnPostCheckout()
        {
            Shopping = false;
            ViewCart = false;
            Checkout = true;

            return Page();
        }
    }
}

Tools R us Sale/Team2WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tools R us Sale/Team2WebApp/Pages/Shared/Sales/Sale.cshtml
@page
@model Team2WebApp.Pages.Shared.Sales.SaleModel
@{
    ViewData["Title"] = "Sale page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to eTools Sale</h1>
    <nav>
        <ul>
            <li><a href="#">Shopping</a></li>
            <li><a href="#">Cart View</a></li>
            <li><a href="#">Check Out</a></li>
            <li><a href="#">Return</a></li>
        </ul>
    </nav>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<form method="post">
    @Model.Feedback
    @if (Model.Shopping)
    {
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Categories)
                {
                    <tr>
                        <td>
                            <input type="hidden" name="Categories.Index" value="@item.CategoryID" />
                            <button type="submit" name="CategoryId" value="@item.CategoryID" asp-page-handler="CategoryItems">
                                @item.Description
                            </button>
                        </td>
                        <td>
                            <input type="hidden" name="Categories[@item.CategoryID].CategoryID" value="@item.CategoryID" readonly />
                            <input type="hidden" name="Categories[@item.CategoryID].Count" value="@item.Count" readonly />
                            @item.Count
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Description</th>
                    <th>QuantityOnHand</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.StockItems != null)
                {
                    @foreach (var item in Model.StockItems)
                    {
                        <tr>
                            <td>
                                <input type="hidden" name="StockItems.Index" value="@item.StockItemID" />
                                <button type="submit" name="StockItemID" value="@item.StockItemID" asp-page-handler="AddItems">
                                    Add
                                </button>
                            </td>
                            <td>
                                <span>1</span>
                            </td>
                            <td>
                                <input type="hidden" name="StockItems[@item.StockItemID].StockItemID" value="@item.StockItemID" readonly />
                                <input type="hidden" name="StockItems[@item.StockItemID].Description" value="@item.Description" readonly />
                                <input type="hidden" name="StockItems[@item.StockItemID].price" value="@item.price" readonly />
                                @item.price @item.Description
                            </td>
                            <td>
                                <input type="hidden" name="StockItems[@item.StockItemID].QuantityOnHand" value="@item.QuantityOnHand" readonly />
                                @item.QuantityOnHand
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <button type="submit" asp-page-handler="Cart">
            Cart
        </button>
    }
    else if (Model.ViewCart)
    {
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.SaleCarts != null)
                {
                    @foreach (var item in Model.SaleCarts)
                    {
                        <tr>
                            <td>
                                <input type="hidden" name="SaleCarts.Index" value="@item.StockItemID" />
                                <input type="hidden" name="SaleCarts[@item.StockItemID].StockItemID" value="@item.StockItemID" readonly />
                                <input type="hidden" name="SaleCarts[@item.StockItemID].Description" value="@item.Description" readonly />
                                @item.Description
                            </td>
                            <td>
                                <input type="hidden" name="SaleCarts[@item.StockItemID].price" value="@item.price" readonly />
                                @item.price
                            </td>
                            <td>
                                <input type="hidden" name="SaleCarts[@item.StockItemID].Total" value="@item.Total" readonly />
                                @item.Total
                            </td>
                            <td>
                                <button type="submit" name="StockItemID" value="@item.StockItemID" asp-page-handler="RemoveItem">
                                    Remove
                                </button>
                            </td>
                            <td>
                               <input type="text" name="SaleCarts[@item.StockItemID].Quantity" value="@item.Quantity" />
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <button type="submit" asp-page-handler="Shopping">
            Shopping
        </button>
        <button type="submit" asp-page-handler="Checkout">
            Checkout
        </button>
    }
    else
    {
        <button type="submit" asp-page-handler="Cart">
            Cart
        </button>
    }

    @if (Model.SaleCarts != null)
    {
        @foreach (var item in Model.SaleCarts)
        {
            <input type="hidden" name="SaleCarts.Index" value="@item.StockItemID" />
            <input type="hidden" name="SaleCarts[@item.StockItemID].StockItemID" value="@item.StockItemID" readonly />
            <input type="hidden" name="SaleCarts[@item.StockItemID].Description" value="@item.Description" readonly />
            <input type="hidden" name="SaleCarts[@item.StockItemID].Quantity" value="@item.Quantity" readonly />
            <input type="hidden" name="SaleCarts[@item.StockItemID].price" value="@item.price" readonly />
            <input type="hidden" name="SaleCarts[@item.StockItemID].Total" value="@item.Total" readonly />
        }
    }
</form>

Tools R us Sale/Team2WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Team2WebApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Team2WebApp.styles.css" asp-append-version="true" />
    @RenderSection("CustomCSS",required:false)
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                <a asp-area="" asp-page="/Index">Team2WebApp</a>
                <button type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                </li>
                <li>
                    <a asp-area="" asp-page="/Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-page="/Privacy">Privacy</a>
                </li>      
                <li>
                    <a asp-area="" asp-page="Shared/Sales/Sale">Sale</a>
                </li> 
                <partial name="_LoginPartial" />
            </ul>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div>
            &copy; 2022 - Team2WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>